### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ishnit** [ayushoriginal/HandWritingRecognition-CNN#1]
I am relatively new to python and i am getting this error:
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    (X_train,y_train),(X_val,y_val) = get_mnist_data()
  File "train.py", line 16, in get_mnist_data
    labels = data[[0]].values.ravel()
  File "/home/ishnit/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 1958, in __getitem__
    return self._getitem_array(key)
  File "/home/ishnit/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2002, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/ishnit/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 1231, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: '[0] not in index'

**Comment by EvanCoh** [comment]
I get the same error. Is it because of python 3.5 ?

**Comment by PR-Iyyer** [comment]
Getting same error for me as well.  :(

**Comment by PR-Iyyer** [comment]
i got that error corrected by changing the line number 16 to `labels = data.iloc[:,:1].values.ravel()`
